
spring.application.name=admin-server

#port config
server.port=8090

#eureka config
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=127.0.0.1	

#admin server config
spring.config.import=optional:classpath:secret.properties

#exception hide
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=ERROR