
spring.application.name=classification-service

#port config
server.port=8086

#Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#api key
spring.config.import=optional:classpath:secret.properties
