
spring.application.name=classification-service

#port config
server.port=8086

#Eureka config
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=127.0.0.1

#api key
spring.config.import=optional:classpath:secret.properties


#actuators config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always