
spring.application.name=analytics-service

#server config
server.port=8089

#MySQL Configuration for CQRS Read model
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/analytics_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#eureka config
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka
eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true

#kafka config
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


#Redis config
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

#actuators config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always