
spring.application.name=api-gateway

#server port
server.port=8085

#Eureka config
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka

#Gateway routing

#Auth service routes (index 0)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Auth Filter 0: Redis Rate Limiter
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

# Auth Filter 1: Resilience4j Circuit Breaker
spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=authCircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/auth


#Grievance service routes (index 1)
spring.cloud.gateway.routes[1].id=grievance-service
spring.cloud.gateway.routes[1].uri=lb://GRIEVANCE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/grievance/**

# Grievance Filter 0: Resilience4j Circuit Breaker
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=grievanceCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/grievance


#Analytics service routes (index 2)
spring.cloud.gateway.routes[2].id=analytics-service
spring.cloud.gateway.routes[2].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/analytics/**


# Resilience4j Tuning
resilience4j.circuitbreaker.instances.authCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authCircuitBreaker.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.authCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.timelimiter.configs.default.timeoutDuration=15s
resilience4j.timelimiter.instances.grievanceCircuitBreaker.timeoutDuration=15s


#Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379



#Spring Boot actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
