
spring.application.name=api-gateway

#server port
server.port=8085

#Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Gateway routing
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=grievance-service
spring.cloud.gateway.routes[1].uri=lb://GRIEVANCE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/grievance/**


#Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Rate limiting config
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

