
spring.application.name=api-gateway

#server port
server.port=8085

#Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Gateway routing
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**